Change db to postgres and create volunteers table
Code-For-Chicago/Voma-backend pull request #4
Opened 2021-07-10 01:14 UTC by kylefarmer85

[ticket](https://trello.com/c/E4L3u19p/166-voma-create-postgresql-table-to-store-volunteer-data)

The app was using sqlite3 as the database, so I changed it to Postgres by adding the 'pg' gem and editing config/database.yml. I created the `volunteers` table based on the description in the ticket.

2021-07-11 14:34 UTC, daleinen7 requested changes
And not so much a request but would it be worth while to have a file like `example.env` with the environment variables that the project needs (obviously with blank values) so when new people join the team it's clear what their .env needs to get the project up and running?

Or do you think that would that cause more problems than it would solve?

2021-07-11 14:34 UTC, daleinen7 commented on Gemfile
>  # Use sqlite3 as the database for Active Record
Might as well delete this comment too

2021-07-11 14:34 UTC, daleinen7 commented on Gemfile
> +# gem 'sqlite3', '~> 1.4'
Might as well delete this comment too

2021-07-12 20:06 UTC, kylefarmer85 commented
I think that could be useful, maybe on a separate ticket? I'm not sure what environment variables would be needed.

2021-07-12 20:10 UTC, Donovon commented
> I think that could be useful, maybe on a separate ticket? I'm not sure what environment variables would be needed.

I agree. We should create a new ticket and discuss it as a group.

2021-07-12 20:44 UTC, daleinen7 approved these changes
Looks good to me.

2021-07-12 20:51 UTC, merged