Create volunteers show endpoint
Code-For-Chicago/Voma-backend pull request #5
Opened 2021-07-14 03:24 UTC by kylefarmer85

[ticket](https://trello.com/c/RJbvvxdU/168-voma-create-endpoint-to-retrieve-data-from-volunteer-table)

I generated a VolunteersController and created a show action to retrieve a single volunteer's data. Also created the corresponding route. 

I created the volunteers controller with an api namespace, so the endpoint is /api/volunteers/:id

2021-07-14 13:50 UTC, jrapala requested changes

2021-07-14 13:50 UTC, jrapala commented on app/controllers/api/volunteers_controller.rb
> +  def show
Can we add a comment that this is GET /volunteers/:id route?

2021-07-14 13:53 UTC, jrapala commented on config/routes.rb
> +  namespace :api do
Can we version this? `v1`?

2021-07-16 00:48 UTC, jrapala requested changes

2021-07-16 00:48 UTC, jrapala commented on app/controllers/api/v1/volunteers_controller.rb
> +  # GET /api/vi/volunteers/:id
Should be `/v1/`

2021-07-16 00:48 UTC, jrapala commented on app/controllers/api/v1/volunteers_controller.rb
> +      render json: {error: "Volunteer not found"}
I did not get this error message. I got "Not Found" instead.

```
{
    "status": 404,
    "error": "Not Found",
    "exception": "#<ActiveRecord::RecordNotFound: Couldn't find Volunteer with 'id'=0>",
    "traces": {
        "Application Trace": [
            {
                "exception_object_id": 13740,
                "id": 1,
                "trace": "app/controllers/api/v1/volunteers_controller.rb:5:in `show'"
            }
        ],
        "Framework Trace": [
            {
                "exception_object_id": 13740,
                "id": 0,
                "trace": "activerecord (6.1.4) lib/active_record/core.rb:338:in `find'"
            },
            {
```

2021-07-16 01:14 UTC, jrapala submitted a review, later dismissed

2021-07-16 01:14 UTC, jrapala commented on app/controllers/api/v1/volunteers_controller.rb
> +      render json: volunteer
Can we camelCase the keys please? 🙏

```
{
    "id": 1,
    "name": "test name",
    "email": "test email",
    "slack_user_id": null,
    "pronouns": null,
    "primary_skills": null,
    "secondary_skills": null,
    "employer": null,
    "student": null,
    "assigned_projects": null,
    "job_title": null,
    "created_at": "2021-07-16T01:06:27.770Z",
    "updated_at": "2021-07-16T01:06:27.770Z"
}
```

2021-07-28 04:55 UTC, Ryan-Koch approved these changes

2021-07-28 05:55 UTC, merged