add setup documentation
Code-For-Chicago/Voma-backend pull request #7
Opened 2021-07-29 18:46 UTC by cgundy

I'm still having permission issues, so I wasn't able to push directly to this repo.

I'm new to Ruby, so please comment with any other suggestions or tips for setup. I ran into several issues, so I added a section on troubleshooting in case anyone ran into these same issues. But if you think any of these things are too obvious and clutter the README, I'm happy to remove them.

2021-07-30 15:37 UTC, daleinen7 approved these changes
This looks great to me.

2021-07-31 16:28 UTC, cgundy commented
> This looks great to me. The only other idea I'd have is maybe to move the trouble shooting to the bottom? But I definitely think it should be there, and it didn't read as cluttered to me.

Thanks! It might be hard to tell with how github displays changes, but they are at the bottom. 👍

2021-08-02 18:12 UTC, aaronreba commented
Does `brew` also start up a database instance for postgres related commands? I can make a small writeup on using the postgres commands directly for starting a dedicated project-specific instance for anyone who has installed postgres using yum/apt or compiled postgres from source.

2021-08-02 19:20 UTC, jrapala requested changes
Just a couple of small comments

2021-08-02 19:20 UTC, jrapala commented on README.md
> +Some issues can arrise if you have different versions of Ruby installed or if you previously weren't using `rbenv`. Some helpful troubleshooting steps are:
Typo: `arrise` should be `arise`

2021-08-02 19:20 UTC, jrapala commented on README.md
> +`bundle install`
We should probably include instructions on how to install `bundler` as well.

2021-08-02 19:20 UTC, jrapala commented on README.md
> +### Troublshooting
Typo: `Trobulshooting` should be `Trobuleshooting`

2021-08-06 21:35 UTC, cgundy commented
> Does `brew` also start up a database instance for postgres related commands? I can make a small writeup on using the postgres commands directly for starting a dedicated project-specific instance for anyone who has installed postgres using yum/apt or compiled postgres from source.

I believe `rake db:setup` starts up the db. But yeah having more instructions would be very helpful!

2021-08-09 16:03 UTC, aaronreba commented
> > Does `brew` also start up a database instance for postgres related commands? I can make a small writeup on using the postgres commands directly for starting a dedicated project-specific instance for anyone who has installed postgres using yum/apt or compiled postgres from source.
> 
> I believe `rake db:setup` starts up the db. But yeah having more instructions would be very helpful!

I've added a gist for starting a postgres database server with the cases I've thought of. https://gist.github.com/aaronreba/ce9619a8270e64cafa630d826d888092

2021-08-09 23:56 UTC, cgundy commented
@jrapala is this PR good to merge?

2021-09-06 16:12 UTC, merged